---

# - name: Delete a file
#   win_file:
# #   path: C:/temp/test_1.bat
#     path: C:/temp/test_1.ps1
#     state: absent

- name: Copy a file
  win_copy: 
   src: test_1.bat
   dest: C:/temp/test_1.bat
#  src: test_1.ps1
#  dest: C:/temp/test_1.ps1
   force: yes
   mode: 0777
  register: output
  
- name: Execute batch
  win_shell: C:/temp/test_1.bat
 #win_shell: C:/temp/test_1.ps1

  register: output
  
- name: Show output
  debug:
    msg: "{{ ansible_facts['ip_addresses'] }} is the current IP address"
    
    
- name: Check admin & pass
  win_user:
    name: ayu
    password: B0bP4ssw0rd
    state: present
    groups:
      - Users
    
     
     
  

