---
- name: execute batch
  win_command: C:\temp\test_1.bat
  register: output
  

  
- name: Checking if a file exists
  win_stat: 
   path: "C:\temp\test_1.bat"
  register: output 
  
- name: report if a file exists
  debug: 
    msg: "The file exists"
  when: output.stat.exists
  
- debug:
   msg:      
   - "{{ output }}"  
  

