---
- name: execute batch
  win_command: C:\temp\test_1.bat
  register: output
  
 
  
- name: report if a file exists
  debug: 
    msg: "The file exists"
  when: output.exists
  
- debug:
   msg:      
   - "{{ output }}"  
  

