---
- name: execute batch
  win_command: C:\temp\test_1.bat
  register: output
  
- debug:
   msg:      
   - "{{ output }}"  
   
- name: Checking if file exists
  stat: 
   path: "C:\temp\test_1.bat"
  register: file_data
  
- name: report if a file exists
  debug: 
    msg: "The file exists"
  when: file_data.stat.exists
  

  

